### ISSUE TITLE
FR: Set a (soft) limit

### ISSUE THREAD

**Issue by mikesnoeren** [nstCactus/craft-disk-usage-widget#1]
A lot of people give their users a soft limit on disk usage as hard limits can get things to corrupt. It would be great if you could set a soft disk usage limit, so the user can see how much they 'have left' or how much they are 'over their limit'.

As of now, there's no way to check this easily in Craft..

**Comment by nstcactus** [comment]
Version 1.2.0 and 2.2.0 are out with that change.
